POST http://localhost:8080/save
Content-Type: application/json

{
  "fileName": "DtoTest.pdf",
  "data": "QUY5OEM3NUExRDA3MkJGPl0gL1ByZXYgMjczMzE2L1hSZWZTdG0gMjcwMTU0Pj4NCnN0YXJ0eHJlZg0KMjk5MzM5DQolJUVPRg=="
}

###

GET http://localhost:8080/downloadPdf/1
Accept: application/pdf

###

GET http://localhost:8080/downloadPdfByFileName/spsm3.pdf
Accept: application/pdf
