POST http://localhost:8080/save
Content-Type: application/json

{
  "fileName": "example1337.pdf",
  "data": "SGVsbG8gd29ybGQh",
  "uploadTime": "2024-09-17T12:34:56"
}

###

GET http://localhost:8080/downloadPdf/9
Accept: application/pdf
